version: '3'

services:
  app-dev:
    image: python
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    user: "1000:999"
    volumes:
    - ./../..:/app
    labels:
      - "author=swoldanski"
    command: watch -n 10 -t pytest -v
